# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara'
require 'capybara/dsl'
require "capybara/cucumber"
require 'factory_girl'


World(FactoryGirl::Syntax::Methods)



Capybara.register_driver :selenium_chrome do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end
Capybara.default_driver = :selenium_chrome

ActionController::Base.allow_rescue = false

Cucumber::Rails::Database.javascript_strategy = :truncation

